name: Scala Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: sbt update
        shell: bash
        run: sbt update

      - name: Run tests
        shell: bash
        run: sbt test
